/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EstimatedDeliveryDate
 */
export interface EstimatedDeliveryDate {
    /**
     * Please indicate if requesting to get EDD for this shipment. <br>          QDDF - is the fastest ('docs') transit time as quoted to the customer at booking or shipment creation. No custom clearance is considered. <br>          QDDC - constitutes DHL's service commitment as quoted at booking/shipment creation. QDDc builds in clearance time, and potentially other special perational non-transport component(s), when relevant.
     * @type {boolean}
     * @memberof EstimatedDeliveryDate
     */
    isRequested: boolean;
    /**
     * Please indicate the EDD type being requested
     * @type {string}
     * @memberof EstimatedDeliveryDate
     */
    typeCode?: EstimatedDeliveryDateTypeCodeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum EstimatedDeliveryDateTypeCodeEnum {
    QDDC = 'QDDC',
    QDDF = 'QDDF'
}

