/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PickupPickupDetails } from './pickup-pickup-details';
import { PickupPickupRequestorDetails } from './pickup-pickup-requestor-details';
import { PickupSpecialInstructions } from './pickup-special-instructions';
/**
 * 
 * @export
 * @interface Pickup
 */
export interface Pickup {
    /**
     * Please advise if a pickup is needed for this shipment
     * @type {boolean}
     * @memberof Pickup
     */
    isRequested: boolean;
    /**
     * The latest time the location premises is available to dispatch the DHL Express shipment. (HH:MM) 
     * @type {string}
     * @memberof Pickup
     */
    closeTime?: string;
    /**
     * Provides information on where the package should be picked up by DHL courier.
     * @type {string}
     * @memberof Pickup
     */
    location?: string;
    /**
     * Details special pickup instructions you may wish to send to the DHL Courier.
     * @type {Array<PickupSpecialInstructions>}
     * @memberof Pickup
     */
    specialInstructions?: Array<PickupSpecialInstructions>;
    /**
     * 
     * @type {PickupPickupDetails}
     * @memberof Pickup
     */
    pickupDetails?: PickupPickupDetails;
    /**
     * 
     * @type {PickupPickupRequestorDetails}
     * @memberof Pickup
     */
    pickupRequestorDetails?: PickupPickupRequestorDetails;
}
