/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidCharges
 */
export interface SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidCharges {
    /**
     * Please enter type of prepaid charge. At this moment only freight is supported
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidCharges
     */
    typeCode: SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesTypeCodeEnum;
    /**
     * Please enter currency for the value you have entered into value field
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidCharges
     */
    currency: string;
    /**
     * Please enter nominal value related to the charge
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidCharges
     */
    value: number;
    /**
     * Please enter method you have used to pay the charges. At this moment only cash is supported
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidCharges
     */
    method: SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesMethodEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesTypeCodeEnum {
    Freight = 'freight'
}
/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesMethodEnum {
    Cash = 'cash'
}

