/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dimensions2 } from './dimensions2';
import { Dimensions3 } from './dimensions3';
import { SupermodelIoLogisticsExpressReference } from './supermodel-io-logistics-express-reference';
import { SupermodelIoLogisticsExpressTrackingResponseEvents1 } from './supermodel-io-logistics-express-tracking-response-events1';
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressTrackingResponsePieces
 */
export interface SupermodelIoLogisticsExpressTrackingResponsePieces {
    /**
     * 
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    number?: number;
    /**
     * 
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    typeCode?: string;
    /**
     * 
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    shipmentTrackingNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    trackingNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    description?: string;
    /**
     * The weight of the package.
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    weight?: number;
    /**
     * The weight of the package.
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    dimensionalWeight?: number;
    /**
     * The weight of the package.
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    actualWeight?: number;
    /**
     * 
     * @type {Dimensions2}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    dimensions?: Dimensions2;
    /**
     * 
     * @type {Dimensions3}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    actualDimensions?: Dimensions3;
    /**
     * 
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    unitOfMeasurements?: string;
    /**
     * 
     * @type {Array<SupermodelIoLogisticsExpressReference>}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    shipperReferences?: Array<SupermodelIoLogisticsExpressReference>;
    /**
     * 
     * @type {Array<SupermodelIoLogisticsExpressTrackingResponseEvents1>}
     * @memberof SupermodelIoLogisticsExpressTrackingResponsePieces
     */
    events: Array<SupermodelIoLogisticsExpressTrackingResponseEvents1>;
}
