/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupermodelIoLogisticsExpressAccount } from './supermodel-io-logistics-express-account';
import { SupermodelIoLogisticsExpressPackageRR } from './supermodel-io-logistics-express-package-rr';
import { SupermodelIoLogisticsExpressRateRequestCustomerDetails } from './supermodel-io-logistics-express-rate-request-customer-details';
import { SupermodelIoLogisticsExpressRateRequestMonetaryAmount } from './supermodel-io-logistics-express-rate-request-monetary-amount';
import { SupermodelIoLogisticsExpressRateRequestProductsAndServices } from './supermodel-io-logistics-express-rate-request-products-and-services';
import { SupermodelIoLogisticsExpressValueAddedServicesRates } from './supermodel-io-logistics-express-value-added-services-rates';
/**
 * Definition of /rates request message
 * @export
 * @interface SupermodelIoLogisticsExpressRateRequest
 */
export interface SupermodelIoLogisticsExpressRateRequest {
    /**
     * 
     * @type {SupermodelIoLogisticsExpressRateRequestCustomerDetails}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    customerDetails: SupermodelIoLogisticsExpressRateRequestCustomerDetails;
    /**
     * Please enter all the DHL Express accounts and types to be used for this shipment
     * @type {Array<SupermodelIoLogisticsExpressAccount>}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    accounts?: Array<SupermodelIoLogisticsExpressAccount>;
    /**
     * Please enter DHL Express Global Product code
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    productCode?: string;
    /**
     * Please enter DHL Express Local Product code
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    localProductCode?: string;
    /**
     * Please use if you wish to filter the response by value added services
     * @type {Array<SupermodelIoLogisticsExpressValueAddedServicesRates>}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    valueAddedServices?: Array<SupermodelIoLogisticsExpressValueAddedServicesRates>;
    /**
     * Please use if you wish to filter the response by product(s) and/or value added services
     * @type {Array<SupermodelIoLogisticsExpressRateRequestProductsAndServices>}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    productsAndServices?: Array<SupermodelIoLogisticsExpressRateRequestProductsAndServices>;
    /**
     * payerCountryCode is to be provided if your profile has been enabled to view rates without an account number (this will provide DHL Express published rates for the payer country)
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    payerCountryCode?: string;
    /**
     * Identifies the date and time the package is tendered. Both the date and time portions of the string are expected to be used. The date should not be a past date or a date more than 10 days in the future. The time is the local time of the shipment based on the shipper's time zone. The date component must be in the format: YYYY-MM-DD; the time component must be in the format: HH:MM:SS using a 24 hour clock. The date and time parts are separated by the letter T (e.g. 2006-06-26T17:00:00 GMT+01:00).
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    plannedShippingDateAndTime: string;
    /**
     * Please enter Unit of measurement - metric,imperial
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    unitOfMeasurement: SupermodelIoLogisticsExpressRateRequestUnitOfMeasurementEnum;
    /**
     * For customs purposes please advise if your shipment is dutiable (true) or non dutiable (false)
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    isCustomsDeclarable: boolean;
    /**
     * Please provide monetary amount related to your shipment, for example shipment declared value
     * @type {Array<SupermodelIoLogisticsExpressRateRequestMonetaryAmount>}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    monetaryAmount?: Array<SupermodelIoLogisticsExpressRateRequestMonetaryAmount>;
    /**
     * Please set this to ture to receive all valuda added services for each product availabe
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    requestAllValueAddedServices?: boolean;
    /**
     * Please set this to true to filter out all products which needs DHL Express special customer agreement
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    returnStandardProductsOnly?: boolean;
    /**
     * Please set this to true in case you want to receive products which are not available on planned shipping date but next available day
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    nextBusinessDay?: boolean;
    /**
     * Please select which type of priducts you are interested in
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    productTypeCode?: SupermodelIoLogisticsExpressRateRequestProductTypeCodeEnum;
    /**
     * Here you can define properties per package
     * @type {Array<SupermodelIoLogisticsExpressPackageRR>}
     * @memberof SupermodelIoLogisticsExpressRateRequest
     */
    packages: Array<SupermodelIoLogisticsExpressPackageRR>;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressRateRequestUnitOfMeasurementEnum {
    Metric = 'metric',
    Imperial = 'imperial'
}
/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressRateRequestProductTypeCodeEnum {
    All = 'all',
    DayDefinite = 'dayDefinite',
    TimeDefinite = 'timeDefinite'
}

