/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomerReferences
 */
export interface SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomerReferences {
    /**
     * Please provide the line item reference type code
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomerReferences
     */
    typeCode: SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomerReferencesTypeCodeEnum;
    /**
     * Please provide the line item reference
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomerReferences
     */
    value: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomerReferencesTypeCodeEnum {
    AFE = 'AFE',
    BRD = 'BRD',
    DGC = 'DGC',
    AAJ = 'AAJ',
    INB = 'INB',
    MAK = 'MAK',
    ALX = 'ALX',
    PAN = 'PAN',
    PON = 'PON',
    ABW = 'ABW',
    SE = 'SE',
    SON = 'SON',
    OID = 'OID',
    DTC = 'DTC',
    DTM = 'DTM',
    DTQ = 'DTQ',
    DTR = 'DTR',
    ITR = 'ITR',
    MID = 'MID',
    OED = 'OED',
    OET = 'OET',
    OOR = 'OOR',
    SME = 'SME',
    USM = 'USM',
    AAM = 'AAM',
    CFR = 'CFR',
    DOM = 'DOM',
    FOR = 'FOR',
    USG = 'USG',
    MAT = 'MAT',
    NLR = 'NLR'
}

