/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Dimensions1 } from './dimensions1';
/**
 * Package defintion for rating related services
 * @export
 * @interface SupermodelIoLogisticsExpressPackageRR
 */
export interface SupermodelIoLogisticsExpressPackageRR {
    /**
     * Please contact your DHL Express representative if you wish to use a DHL specific package otherwise ignore this element.
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressPackageRR
     */
    typeCode?: SupermodelIoLogisticsExpressPackageRRTypeCodeEnum;
    /**
     * The weight of the package.
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressPackageRR
     */
    weight: number;
    /**
     * 
     * @type {Dimensions1}
     * @memberof SupermodelIoLogisticsExpressPackageRR
     */
    dimensions: Dimensions1;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressPackageRRTypeCodeEnum {
    _3BX = '3BX',
    _2BC = '2BC',
    _2BP = '2BP',
    CE1 = 'CE1',
    _7BX = '7BX',
    _6BX = '6BX',
    _4BX = '4BX',
    _2BX = '2BX',
    _1CE = '1CE',
    WB1 = 'WB1',
    WB3 = 'WB3',
    XPD = 'XPD',
    _8BX = '8BX',
    _5BX = '5BX',
    WB6 = 'WB6',
    TBL = 'TBL',
    TBS = 'TBS',
    WB2 = 'WB2'
}

