/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressRatesPriceBreakdown1
 */
export interface SupermodelIoLogisticsExpressRatesPriceBreakdown1 {
    /**
     * If a breakdown is provided, details can either be; 'TAX',<br>                              'DISCOUNT'
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesPriceBreakdown1
     */
    priceType?: string;
    /**
     * Discount or tax type codes as provided by DHL Express. Example values;<br>                              For discount;<br>                              P â€“ promotional<br>                              S â€“ special<br>                              - \"DISCOUNT\"
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesPriceBreakdown1
     */
    typeCode?: string;
    /**
     * The actual amount of the discount/tax
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressRatesPriceBreakdown1
     */
    price?: number;
    /**
     * Percentage of the discount/tax
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressRatesPriceBreakdown1
     */
    rate?: number;
    /**
     * The base amount of the service charge
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressRatesPriceBreakdown1
     */
    basePrice?: number;
}
