/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfoTrackingNumberBarcodes } from './supermodel-io-logistics-express-create-shipment-response-barcode-info-tracking-number-barcodes';
/**
 * Here you can find barcode details in base64
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo
 */
export interface SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo {
    /**
     * Barcode base64 encoded airwaybill number
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo
     */
    shipmentIdentificationNumberBarcodeContent?: string;
    /**
     * Barcode base64 image of origin service area code, destination service area code and global product code
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo
     */
    originDestinationServiceTypeBarcodeContent?: string;
    /**
     * Barcode base64 image of DHL routing code
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo
     */
    routingBarcodeContent?: string;
    /**
     * Here you can find barcode details for each piece
     * @type {Array<SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfoTrackingNumberBarcodes>}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo
     */
    trackingNumberBarcodes?: Array<SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfoTrackingNumberBarcodes>;
}
