/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalCharges
 */
export interface SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalCharges {
    /**
     * Please provide the charge value
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalCharges
     */
    value: number;
    /**
     * Please enter charge caption
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalCharges
     */
    caption?: string;
    /**
     * Please enter charge type
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalCharges
     */
    typeCode: SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalChargesTypeCodeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalChargesTypeCodeEnum {
    Admin = 'admin',
    Delivery = 'delivery',
    Documentation = 'documentation',
    Expedite = 'expedite',
    Export = 'export',
    Freight = 'freight',
    FuelSurcharge = 'fuel_surcharge',
    Logistic = 'logistic',
    Other = 'other',
    Packaging = 'packaging',
    Pickup = 'pickup',
    Handling = 'handling',
    Vat = 'vat',
    Insurance = 'insurance',
    ReverseCharge = 'reverse_charge'
}

