/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsBuyerDetails } from './supermodel-io-logistics-express-create-shipment-request-customer-details-buyer-details';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsExporterDetails } from './supermodel-io-logistics-express-create-shipment-request-customer-details-exporter-details';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsImporterDetails } from './supermodel-io-logistics-express-create-shipment-request-customer-details-importer-details';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsPayerDetails } from './supermodel-io-logistics-express-create-shipment-request-customer-details-payer-details';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsReceiverDetails } from './supermodel-io-logistics-express-create-shipment-request-customer-details-receiver-details';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsSellerDetails } from './supermodel-io-logistics-express-create-shipment-request-customer-details-seller-details';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsShipperDetails } from './supermodel-io-logistics-express-create-shipment-request-customer-details-shipper-details';
/**
 * Here you need to define all the parties needed to ship the package
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails
 */
export interface SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails {
    /**
     * 
     * @type {SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsShipperDetails}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails
     */
    shipperDetails: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsShipperDetails;
    /**
     * 
     * @type {SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsReceiverDetails}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails
     */
    receiverDetails: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsReceiverDetails;
    /**
     * 
     * @type {SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsBuyerDetails}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails
     */
    buyerDetails?: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsBuyerDetails;
    /**
     * 
     * @type {SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsImporterDetails}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails
     */
    importerDetails?: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsImporterDetails;
    /**
     * 
     * @type {SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsExporterDetails}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails
     */
    exporterDetails?: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsExporterDetails;
    /**
     * 
     * @type {SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsSellerDetails}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails
     */
    sellerDetails?: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsSellerDetails;
    /**
     * 
     * @type {SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsPayerDetails}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails
     */
    payerDetails?: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsPayerDetails;
}
