/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupermodelIoLogisticsExpressAccount } from './supermodel-io-logistics-express-account';
import { SupermodelIoLogisticsExpressDocumentImages } from './supermodel-io-logistics-express-document-images';
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressImageUploadRequest
 */
export interface SupermodelIoLogisticsExpressImageUploadRequest {
    /**
     * Please provide Shipment Identification number (AWB number)
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressImageUploadRequest
     */
    shipmentTrackingNumber: string;
    /**
     * 
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressImageUploadRequest
     */
    originalPlannedShippingDate: string;
    /**
     * Please enter all the DHL Express accounts and types to be used for this shipment
     * @type {Array<SupermodelIoLogisticsExpressAccount>}
     * @memberof SupermodelIoLogisticsExpressImageUploadRequest
     */
    accounts: Array<SupermodelIoLogisticsExpressAccount>;
    /**
     * Please enter DHL Express Global Product code
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressImageUploadRequest
     */
    productCode: string;
    /**
     * 
     * @type {SupermodelIoLogisticsExpressDocumentImages}
     * @memberof SupermodelIoLogisticsExpressImageUploadRequest
     */
    documentImages: SupermodelIoLogisticsExpressDocumentImages;
}
