/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressPackageLabelText
 */
export interface SupermodelIoLogisticsExpressPackageLabelText {
    /**
     * Position of the bespoke text
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressPackageLabelText
     */
    position: SupermodelIoLogisticsExpressPackageLabelTextPositionEnum;
    /**
     * Please enter caption to be printed in the tag value
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressPackageLabelText
     */
    caption: string;
    /**
     * Please enter value to be printed for the respective tag in caption
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressPackageLabelText
     */
    value: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressPackageLabelTextPositionEnum {
    Left = 'left',
    Right = 'right'
}

