/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupermodelIoLogisticsExpressUploadInvoiceDataRequestOutputImagePropertiesImageOptions } from './supermodel-io-logistics-express-upload-invoice-data-request-output-image-properties-image-options';
/**
 * Here you can set invoice properties
 * @export
 * @interface SupermodelIoLogisticsExpressUploadInvoiceDataRequestOutputImageProperties
 */
export interface SupermodelIoLogisticsExpressUploadInvoiceDataRequestOutputImageProperties {
    /**
     * Here the image options are defined for label, waybillDoc, invoice, receipt and QRcode
     * @type {Array<SupermodelIoLogisticsExpressUploadInvoiceDataRequestOutputImagePropertiesImageOptions>}
     * @memberof SupermodelIoLogisticsExpressUploadInvoiceDataRequestOutputImageProperties
     */
    imageOptions?: Array<SupermodelIoLogisticsExpressUploadInvoiceDataRequestOutputImagePropertiesImageOptions>;
}
