/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressDocumentImageResponseDocuments
 */
export interface SupermodelIoLogisticsExpressDocumentImageResponseDocuments {
    /**
     * Shipment Tracking Number
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressDocumentImageResponseDocuments
     */
    shipmentTrackingNumber: string;
    /**
     * Identifies type of the document like commercial invoice or waybill, or archived zip documents
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressDocumentImageResponseDocuments
     */
    typeCode: string;
    /**
     * Clearance code or document function whether for import, export or both.  Returned only for customs-entry
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressDocumentImageResponseDocuments
     */
    _function?: SupermodelIoLogisticsExpressDocumentImageResponseDocumentsFunctionEnum;
    /**
     * Identifies image format the document is created in, like PDF, TIFF, or ZIP
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressDocumentImageResponseDocuments
     */
    encodingFormat: string;
    /**
     * Contains base64 encoded document image or archived zip
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressDocumentImageResponseDocuments
     */
    content: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressDocumentImageResponseDocumentsFunctionEnum {
    Import = 'import',
    Export = 'export',
    Both = 'both'
}

