/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
 */
export interface SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions {
    /**
     * Please enter the document type you want to wish set properties for
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    typeCode: SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptionsTypeCodeEnum;
    /**
     * Please enter DHL Express document template name.<br>                        Sample Transport label templates:<br>                        ECOM26_84_A4_001 <br>                        ECOM26_84_001 - default<br>                        ECOM_TC_A4<br>                        ECOM26_A6_002<br>                        ECOM26_84CI_001<br>                        ECOM26_84CI_002 - supported single customer barcode<br>                        ECOM26_84CI_003 - to be used if customer barcodes are used<br>                        ECOM_A4_RU_002<br>                        <br>                        Sample WaybillDoc templates<br>                        ARCH_8X4_A4_002<br>                        ARCH_8X4 - default<br>                        ARCH_6X4<br>                        ARCH_A4_RU_002<br>                        <br>                        Sample Commercial invoice template<br>                        COMMERCIAL_INVOICE_03 - default<br>                        <br>                        Sample Shipment Receipt template<br>                        SHIP_RECPT_A4_RU_002 - default<br>                        <br>                        Sample QR Code template template<br>                        QR_1_00_LL_PNG_001 - default
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    templateName?: string;
    /**
     * To be used for waybillDoc, invoice, receipt and QRcode. If set to true then the document is provided otherwise not
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    isRequested?: boolean;
    /**
     * To be used for waybillDoc. If set to true then account information will not be printed on the waybillDoc
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    hideAccountNumber?: boolean;
    /**
     * You can ask up to 2 waybillDoc copies to be provided
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    numberOfCopies?: number;
    /**
     * Please advise what type of customs documentation is required
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    invoiceType?: SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptionsInvoiceTypeEnum;
    /**
     * Please enter ISO 3 letters language code for invoice
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    languageCode?: string;
    /**
     * Please enter ISO 2 letters language country code for invoice
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    languageCountryCode?: string;
    /**
     * Please provide the format of the QR Code output format.
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    encodingFormat?: SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptionsEncodingFormatEnum;
    /**
     * DHL Logo to be printed in Transport Label or Waybill Document
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    renderDHLLogo?: boolean;
    /**
     * To print respective Transport Label and Waybill document into A4 margin PDF.<br>                Note: ECOM26_A6_002,ECOM26_84CI_001,ECOM26_84CI_002,ARCH_6X4,ARCH_8X4 template. <br>                This option is applicable only for PDF encodingFormat selection.<br>                false: Transport Label and Waybill document will use default margin settings (default behavior) <br>                true: Transport Label and Waybill document will print into A4 margin PDF
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    fitLabelsToA4?: boolean;
    /**
     * Additional customer label free text that can be printed in certain label.Note: Applicable only to ECOM26_A6_002, ECOM_TC_A4 and ECOM26_84CI_001.
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    labelFreeText?: string;
    /**
     * Additional customer label text that can be printed in certain label.Note: Applicable only to ECOM26_84_A4_001, ECOM_TC_A4 and ECOM26_84CI_001
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions
     */
    labelCustomerDataText?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptionsTypeCodeEnum {
    Label = 'label',
    WaybillDoc = 'waybillDoc',
    Invoice = 'invoice',
    Receipt = 'receipt',
    QrCode = 'qr-code'
}
/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptionsInvoiceTypeEnum {
    Commercial = 'commercial',
    Proforma = 'proforma'
}
/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptionsEncodingFormatEnum {
    Png = 'png'
}

