/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupermodelIoLogisticsExpressAccount } from './supermodel-io-logistics-express-account';
import { SupermodelIoLogisticsExpressPickupRequestCustomerDetails } from './supermodel-io-logistics-express-pickup-request-customer-details';
import { SupermodelIoLogisticsExpressPickupRequestSpecialInstructions } from './supermodel-io-logistics-express-pickup-request-special-instructions';
import { SupermodelIoLogisticsExpressUpdatePickupRequestShipmentDetails } from './supermodel-io-logistics-express-update-pickup-request-shipment-details';
/**
 * UpdatePickup schema definition
 * @export
 * @interface SupermodelIoLogisticsExpressUpdatePickupRequest
 */
export interface SupermodelIoLogisticsExpressUpdatePickupRequest {
    /**
     * Please enter Dispatch confirmation number which identifies the already scheduled pickup
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    dispatchConfirmationNumber: string;
    /**
     * Please enter the shipper account number which was used during the scheduled pickup creation
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    originalShipperAccountNumber: string;
    /**
     * Identifies the date and time the package is ready for pickup Both the date and time portions of the string are expected to be used. The date should not be a past date or a date more than 10 days in the future. The time is the local time of the shipment based on the shipper's time zone. The date component must be in the format: YYYY-MM-DD; the time component must be in the format: HH:MM:SS using a 24 hour clock. The date and time parts are separated by the letter T (e.g. 2006-06-26T17:00:00 GMT+01:00).<br>                           
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    plannedPickupDateAndTime: string;
    /**
     * The latest time the location premises is available to dispatch the DHL Express shipment. (HH:MM) 
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    closeTime?: string;
    /**
     * Provides information on where the package should be picked up by DHL courier. <br>                           
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    location?: string;
    /**
     * Provides information on where the package should be picked up by DHL courier. <br>                           
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    locationType?: SupermodelIoLogisticsExpressUpdatePickupRequestLocationTypeEnum;
    /**
     * 
     * @type {Array<SupermodelIoLogisticsExpressAccount>}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    accounts: Array<SupermodelIoLogisticsExpressAccount>;
    /**
     * Details special pickup instructions you may wish to send to the DHL Courier.
     * @type {Array<SupermodelIoLogisticsExpressPickupRequestSpecialInstructions>}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    specialInstructions?: Array<SupermodelIoLogisticsExpressPickupRequestSpecialInstructions>;
    /**
     * Please provide additional pickup remark
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    remark?: string;
    /**
     * 
     * @type {SupermodelIoLogisticsExpressPickupRequestCustomerDetails}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    customerDetails: SupermodelIoLogisticsExpressPickupRequestCustomerDetails;
    /**
     * Please provide updated details related to shipment you want update the pickup for
     * @type {Array<SupermodelIoLogisticsExpressUpdatePickupRequestShipmentDetails>}
     * @memberof SupermodelIoLogisticsExpressUpdatePickupRequest
     */
    shipmentDetails?: Array<SupermodelIoLogisticsExpressUpdatePickupRequestShipmentDetails>;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressUpdatePickupRequestLocationTypeEnum {
    Business = 'business',
    Residence = 'residence'
}

