/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressRatesPickupCapabilities
 */
export interface SupermodelIoLogisticsExpressRatesPickupCapabilities {
    /**
     * This indicator has values of Y or N, and tells the consumer if the service in the response has a pickup date on the same day as the requested shipment date (per the request).
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressRatesPickupCapabilities
     */
    nextBusinessDay?: boolean;
    /**
     * This is the cutoff time for the service<br>                offered in the response. This represents the latest time (local to origin) which the shipment can be tendered to the courier for that service on that day.
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesPickupCapabilities
     */
    localCutoffDateAndTime?: string;
    /**
     * Pickup cut off time in GMT
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesPickupCapabilities
     */
    gMTCutoffTime?: string;
    /**
     * The DHL earliest time possible for pickup
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesPickupCapabilities
     */
    pickupEarliest?: string;
    /**
     * The DHL latest time possible for pickup
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesPickupCapabilities
     */
    pickupLatest?: string;
    /**
     * The DHL Service Area Code for the origin of the Shipment
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesPickupCapabilities
     */
    originServiceAreaCode?: string;
    /**
     * The DHL Facility Code for the Origin
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesPickupCapabilities
     */
    originFacilityAreaCode?: string;
    /**
     * This is additional transit delays (in days) for shipment picked up from the mentioned city or postal area to arrival at the service area.
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressRatesPickupCapabilities
     */
    pickupAdditionalDays?: number;
    /**
     * Pickup day of the week number
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressRatesPickupCapabilities
     */
    pickupDayOfWeek?: number;
}
