/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesCustomerBarcodes } from './supermodel-io-logistics-express-create-shipment-request-output-image-properties-customer-barcodes';
import { SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesCustomerLogos } from './supermodel-io-logistics-express-create-shipment-request-output-image-properties-customer-logos';
import { SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions } from './supermodel-io-logistics-express-create-shipment-request-output-image-properties-image-options';
/**
 * Here you can modify label, waybillDoc, invoice and receipt properties
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
 */
export interface SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties {
    /**
     * Printer DPI Resolution for X-axis and Y-axis (in DPI) for transport label and waybill document output
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
     */
    printerDPI?: SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesPrinterDPIEnum;
    /**
     * Customer barcodes to be printed on supported transport label templates
     * @type {Array<SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesCustomerBarcodes>}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
     */
    customerBarcodes?: Array<SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesCustomerBarcodes>;
    /**
     * Customer Logo Image to be printed on transport label
     * @type {Array<SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesCustomerLogos>}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
     */
    customerLogos?: Array<SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesCustomerLogos>;
    /**
     * Please provide the format of the output documents. Note that invoice and receipt will always come back as PDF
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
     */
    encodingFormat?: SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesEncodingFormatEnum;
    /**
     * Here the image options are defined for label, waybillDoc, invoice, receipt and QRcode
     * @type {Array<SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions>}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
     */
    imageOptions?: Array<SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesImageOptions>;
    /**
     * When set to true it will generate a single PDF or thermal output file for the Transport Label, a single PDF or thermal output file for the Waybill document and a single PDF file consisting of Commercial Invoice and Shipment Receipt. The default value is false, a single PDF or thermal output image file consists of Transport Label and single PDF or thermal output image file for Waybill Document will be returned in create shipment response.
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
     */
    splitTransportAndWaybillDocLabels?: boolean;
    /**
     * When set to true it will generate a single PDF or thermal output image file consists of Transport Label, Waybill Document, Shipment Receipt and Commercial Invoice.<br>          The default value is false, where a single PDF or thermal output image file consists of Transport Label + Waybill Document and single PDF or thermal output image file for Shipment Receipt and Customs Invoice will be returned.
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
     */
    allDocumentsInOneImage?: boolean;
    /**
     * When set to true it will generate a single PDF or thermal output image file for each page for the Transport Label and single PDF or thermal output image file for Waybill Document will be returned in the create shipment response. The default value is false, a single PDF or thermal output image file for each page for Transport Label and single PDF or thermal output image file for Waybill Document will be returned in create shipment response.
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
     */
    splitDocumentsByPages?: boolean;
    /**
     * When set to true it will generate a single PDF or thermal output image file consisting of Transport Label + Waybill Document, a single file consist of Commercial Invoice and a single file consist of Shipment Receipt. The default value is false, a single PDF or thermal output image file consists of Transport Label + Waybill Document and single PDF or thermal output image file for Shipment Receipt and Customs Invoice will be returned in create shipment response.
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
     */
    splitInvoiceAndReceipt?: boolean;
    /**
     * When set to true it will generate a single PDF file consisting of Transport Label, Waybill Document and Shipment Receipt. The default value is false, a single PDF or thermal output image file consists of Transport Label + Waybill Document and single PDF file for Shipment Receipt will be returned in create shipment response.  Applicable only when #/outputImageProperties/imageOptions/0/typeCode is 'receipt' and #/outputImageProperties/encodingFormat is PDF.
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOutputImageProperties
     */
    receiptAndLabelsInOneImage?: boolean;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesPrinterDPIEnum {
    NUMBER_200 = 200,
    NUMBER_300 = 300
}
/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestOutputImagePropertiesEncodingFormatEnum {
    Pdf = 'pdf',
    Zpl = 'zpl',
    Lp2 = 'lp2',
    Epl = 'epl'
}

