/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Here you can provide data in case you wish to use DHL Express On demand delivery service
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
 */
export interface SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery {
    /**
     * Please choose from one of the delivery options
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
     */
    deliveryOption: SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDeliveryDeliveryOptionEnum;
    /**
     * If delivery option is signatureDelivery please specify location where to leave the shipment
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
     */
    location?: string;
    /**
     * Please enter additional information that might be useful for the DHL Express courier
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
     */
    specialInstructions?: string;
    /**
     * Please provide entry code to gain access to an apartment complex or gate
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
     */
    gateCode?: string;
    /**
     * In ase your deliveryOption is 'neighbour' please specify where to leave the package 
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
     */
    whereToLeave?: SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDeliveryWhereToLeaveEnum;
    /**
     * In case you wish to leave the package with neighbour please provide the neighbour's name
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
     */
    neighbourName?: string;
    /**
     * In case you wish to leave the package with neighbour please provide the neighbour's house number
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
     */
    neighbourHouseNumber?: string;
    /**
     * In case your delivery option is 'signatureRelease' please provide name of the person who is authorized to sign and receive the package
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
     */
    authorizerName?: string;
    /**
     * In case your delivery option is 'servicepoint' please provide unique DHL Express Service point location ID of where the parcel should be delieverd (please contact your local DHL Express Account Manager to obtain the list of the servicepoint IDs)
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
     */
    servicePointId?: string;
    /**
     * for future use
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDelivery
     */
    requestedDeliveryDate?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDeliveryDeliveryOptionEnum {
    Servicepoint = 'servicepoint',
    Neighbour = 'neighbour',
    SignatureRelease = 'signatureRelease'
}
/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestOnDemandDeliveryWhereToLeaveEnum {
    Concierge = 'concierge',
    Neighbour = 'neighbour'
}

