/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoiceCustomerReferences
 */
export interface SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoiceCustomerReferences {
    /**
     * Please provide the invoice reference type code
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoiceCustomerReferences
     */
    typeCode: SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoiceCustomerReferencesTypeCodeEnum;
    /**
     * Please provide the invoice reference
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoiceCustomerReferences
     */
    value: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoiceCustomerReferencesTypeCodeEnum {
    ACL = 'ACL',
    CID = 'CID',
    CN = 'CN',
    CU = 'CU',
    ITN = 'ITN',
    UCN = 'UCN',
    MRN = 'MRN',
    OID = 'OID',
    PON = 'PON',
    RMA = 'RMA',
    AAM = 'AAM',
    ABT = 'ABT',
    ADA = 'ADA',
    AES = 'AES',
    AFD = 'AFD',
    ANT = 'ANT',
    BKN = 'BKN',
    BOL = 'BOL',
    CDN = 'CDN',
    COD = 'COD',
    DSC = 'DSC',
    FF = 'FF',
    FN = 'FN',
    FTR = 'FTR',
    HWB = 'HWB',
    IBC = 'IBC',
    IPP = 'IPP',
    LLR = 'LLR',
    MAB = 'MAB',
    MWB = 'MWB',
    OBC = 'OBC',
    PD = 'PD',
    PRN = 'PRN',
    RTL = 'RTL',
    SID = 'SID',
    SS = 'SS',
    SWN = 'SWN'
}

