/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressProductsDeliveryCapabilities
 */
export interface SupermodelIoLogisticsExpressProductsDeliveryCapabilities {
    /**
     * Delivery Date capabilities considering customs clearance days.<br>                QDDF - is the fastest (\"docs\") transit time as quoted to the customer at booking or shipment creation. No custom clearance is considered.<br>                QDDC - constitutes DHL's service commitment as quoted at booking/shipment creation. QDDc builds in clearance time, and potentially other special operational non-transport component(s), when relevant.
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressProductsDeliveryCapabilities
     */
    deliveryTypeCode?: string;
    /**
     * This is the estimated date/time the shipment will be delivered by for the rated shipment and product listed
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressProductsDeliveryCapabilities
     */
    estimatedDeliveryDateAndTime?: string;
    /**
     * The DHL Service Area Code for the destination of the Shipment
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressProductsDeliveryCapabilities
     */
    destinationServiceAreaCode?: string;
    /**
     * The DHL Facility Code for the Destination
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressProductsDeliveryCapabilities
     */
    destinationFacilityAreaCode?: string;
    /**
     * This is additional transit delays (in days) for shipment delivered to the<br>                mentioned city or postal area following arrival at the service area.
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressProductsDeliveryCapabilities
     */
    deliveryAdditionalDays?: number;
    /**
     * Destination day of the week number
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressProductsDeliveryCapabilities
     */
    deliveryDayOfWeek?: number;
    /**
     * The number of transit days
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressProductsDeliveryCapabilities
     */
    totalTransitDays?: number;
}
