/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupermodelIoLogisticsExpressProductsDeliveryCapabilities } from './supermodel-io-logistics-express-products-delivery-capabilities';
import { SupermodelIoLogisticsExpressRatesDetailedPriceBreakdown } from './supermodel-io-logistics-express-rates-detailed-price-breakdown';
import { SupermodelIoLogisticsExpressRatesItems } from './supermodel-io-logistics-express-rates-items';
import { SupermodelIoLogisticsExpressRatesPickupCapabilities } from './supermodel-io-logistics-express-rates-pickup-capabilities';
import { SupermodelIoLogisticsExpressRatesTotalPrice } from './supermodel-io-logistics-express-rates-total-price';
import { SupermodelIoLogisticsExpressRatesTotalPriceBreakdown } from './supermodel-io-logistics-express-rates-total-price-breakdown';
import { Weight1 } from './weight1';
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressRatesProducts
 */
export interface SupermodelIoLogisticsExpressRatesProducts {
    /**
     * Name of the DHL Express product
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    productName?: string;
    /**
     * This is the global DHL Express product code for which the delivery is feasible respecting the input data from the request.
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    productCode?: string;
    /**
     * This is the local DHL Express product code for which the delivery is feasible respecting the input data from the request.
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    localProductCode?: string;
    /**
     * The country code for the local service used
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    localProductCountryCode?: string;
    /**
     * The NetworkTypeCode element indicates the product belongs to the Day Definite (DD) or Time Definite (TD) network.<br>            Possible Values;<br>            - â€˜DDâ€™, Day Definite product<br>            - â€˜TDâ€™, Time Definite product
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    networkTypeCode?: string;
    /**
     * Indicator that the product only can be offered to customers with prior agreement.
     * @type {boolean}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    isCustomerAgreement?: boolean;
    /**
     * 
     * @type {Weight1}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    weight: Weight1;
    /**
     * 
     * @type {Array<SupermodelIoLogisticsExpressRatesTotalPrice>}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    totalPrice: Array<SupermodelIoLogisticsExpressRatesTotalPrice>;
    /**
     * 
     * @type {Array<SupermodelIoLogisticsExpressRatesTotalPriceBreakdown>}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    totalPriceBreakdown?: Array<SupermodelIoLogisticsExpressRatesTotalPriceBreakdown>;
    /**
     * 
     * @type {Array<SupermodelIoLogisticsExpressRatesDetailedPriceBreakdown>}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    detailedPriceBreakdown?: Array<SupermodelIoLogisticsExpressRatesDetailedPriceBreakdown>;
    /**
     * 
     * @type {SupermodelIoLogisticsExpressRatesPickupCapabilities}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    pickupCapabilities?: SupermodelIoLogisticsExpressRatesPickupCapabilities;
    /**
     * 
     * @type {SupermodelIoLogisticsExpressProductsDeliveryCapabilities}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    deliveryCapabilities?: SupermodelIoLogisticsExpressProductsDeliveryCapabilities;
    /**
     * 
     * @type {Array<SupermodelIoLogisticsExpressRatesItems>}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    items?: Array<SupermodelIoLogisticsExpressRatesItems>;
    /**
     * The date when the rates for DHL products and services is provided
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressRatesProducts
     */
    pricingDate?: string;
}
