/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressAddressCreateShipmentResponse
 */
export interface SupermodelIoLogisticsExpressAddressCreateShipmentResponse {
    /**
     * Postal code
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressAddressCreateShipmentResponse
     */
    postalCode: string;
    /**
     * City name
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressAddressCreateShipmentResponse
     */
    cityName: string;
    /**
     * Country code
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressAddressCreateShipmentResponse
     */
    countryCode: string;
    /**
     * Province or state code
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressAddressCreateShipmentResponse
     */
    provinceCode?: string;
    /**
     * Address line 1
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressAddressCreateShipmentResponse
     */
    addressLine1: string;
    /**
     * Address line 2
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressAddressCreateShipmentResponse
     */
    addressLine2?: string;
    /**
     * Address line 3
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressAddressCreateShipmentResponse
     */
    addressLine3?: string;
    /**
     * Suburb or county name
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressAddressCreateShipmentResponse
     */
    cityDistrictName?: string;
    /**
     * Please enter your state or province name
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressAddressCreateShipmentResponse
     */
    provinceName?: string;
    /**
     * Please enter your country name
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressAddressCreateShipmentResponse
     */
    countryName?: string;
}
