/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressDocumentImagesInner
 */
export interface SupermodelIoLogisticsExpressDocumentImagesInner {
    /**
     * Please provide correct document type you wish to upload<br>        <br>        Possible values;<br>        INV, Invoice<br>        PNV, Proforma<br>        COO, Certificate of Origin<br>        NAF, Nafta Certificate of Origin<br>        CIN, Commercial Invoice<br>        DCL, Custom Declaration<br>        AWB, Air Waybill and Waybill Document
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressDocumentImagesInner
     */
    typeCode?: SupermodelIoLogisticsExpressDocumentImagesInnerTypeCodeEnum;
    /**
     * Please provide the image file format for the document you want to upload
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressDocumentImagesInner
     */
    imageFormat?: SupermodelIoLogisticsExpressDocumentImagesInnerImageFormatEnum;
    /**
     * Please provide the base64 encoded document
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressDocumentImagesInner
     */
    content: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressDocumentImagesInnerTypeCodeEnum {
    INV = 'INV',
    PNV = 'PNV',
    COO = 'COO',
    CIN = 'CIN',
    DCL = 'DCL',
    AWB = 'AWB',
    NAF = 'NAF'
}
/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressDocumentImagesInnerImageFormatEnum {
    PDF = 'PDF',
    PNG = 'PNG',
    GIF = 'GIF',
    TIFF = 'TIFF',
    JPEG = 'JPEG'
}

