/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Please enter information about quantity for this line item
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationQuantity
 */
export interface SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationQuantity {
    /**
     * Please enter number of pieces in the line item
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationQuantity
     */
    value: number;
    /**
     * Please provide correct unit of measurement<br>                        <br>                        Possible values;<br>                        BOX Boxes<br>                        2GM Centigram<br>                        2M Centimeters<br>                        2M3 Cubic Centimeters<br>                        3M3 Cubic Feet<br>                        M3 Cubic Meters<br>                        DPR Dozen Pairs<br>                        DOZ Dozen<br>                        2NO Each<br>                        PCS Pieces<br>                        GM Grams<br>                        GRS Gross<br>                        KG Kilograms<br>                        L Liters<br>                        M Meters<br>                        3GM Milligrams<br>                        3L Milliliters<br>                        X No Unit Required<br>                        NO Number<br>                        2KG Ounces<br>                        PRS Pairs<br>                        2L Gallons<br>                        3KG Pounds<br>                        CM2 Square Centimeters<br>                        2M2 Square Feet<br>                        3M2 Square Inches<br>                        M2 Square Meters<br>                        4M2 Square Yards<br>                        3M Yards
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationQuantity
     */
    unitOfMeasurement: SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationQuantityUnitOfMeasurementEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationQuantityUnitOfMeasurementEnum {
    BOX = 'BOX',
    _2GM = '2GM',
    _2M = '2M',
    _2M3 = '2M3',
    _3M3 = '3M3',
    M3 = 'M3',
    DPR = 'DPR',
    DOZ = 'DOZ',
    _2NO = '2NO',
    PCS = 'PCS',
    GM = 'GM',
    GRS = 'GRS',
    KG = 'KG',
    L = 'L',
    M = 'M',
    _3GM = '3GM',
    _3L = '3L',
    X = 'X',
    NO = 'NO',
    _2KG = '2KG',
    PRS = 'PRS',
    _2L = '2L',
    _3KG = '3KG',
    CM2 = 'CM2',
    _2M2 = '2M2',
    _3M2 = '3M2',
    M2 = 'M2',
    _4M2 = '4M2',
    _3M = '3M'
}

