/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SupermodelIoLogisticsExpressCreateShipmentResponseDocuments } from './supermodel-io-logistics-express-create-shipment-response-documents';
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentResponsePackages
 */
export interface SupermodelIoLogisticsExpressCreateShipmentResponsePackages {
    /**
     * Piece serial number
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponsePackages
     */
    referenceNumber?: number;
    /**
     * Here is provided each piece its Identification number
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponsePackages
     */
    trackingNumber: string;
    /**
     * You can use ths URL to track your shipment by Piece Identification Number
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponsePackages
     */
    trackingUrl?: string;
    /**
     * Here is provided each piece volumetric/ dimensional weight
     * @type {number}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponsePackages
     */
    volumetricWeight?: number;
    /**
     * Here you can find all documents created for the piece's QRcode
     * @type {Array<SupermodelIoLogisticsExpressCreateShipmentResponseDocuments>}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponsePackages
     */
    documents?: Array<SupermodelIoLogisticsExpressCreateShipmentResponseDocuments>;
}
