/* tslint:disable */
/* eslint-disable */
/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SupermodelIoLogisticsExpressCreateShipmentResponseDocuments1
 */
export interface SupermodelIoLogisticsExpressCreateShipmentResponseDocuments1 {
    /**
     * Identifie image format the document is created in, like PDF, JPG etc.
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponseDocuments1
     */
    imageFormat: string;
    /**
     * Contains base64 encoded document image
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponseDocuments1
     */
    content: string;
    /**
     * Identifie type of the document, like invoice, label or receipt
     * @type {string}
     * @memberof SupermodelIoLogisticsExpressCreateShipmentResponseDocuments1
     */
    typeCode: string;
}
